.Dd November 12, 2024
.Dt PLAKAR-VERSION 1
.Os
.Sh NAME
.Nm plakar version
.Nd Display the current version of Plakar
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
The
.Nm
command is used to display the current version of the Plakar software.
This command retrieves and outputs the version string, formatted
according to semantic versioning.
.Sh OPTIONS
No options are available for this command.
.Sh ARGUMENTS
None.
.Sh EXAMPLES
Basic example:
.Bd -literal -offset indent
plakar version
.Ed
.Sh DIAGNOSTICS
.Ex -std
.Bl -tag -width Ds
.It 0
Command completed successfully.
.It >0
General failure occurred, such as an invalid version string.
.El
.Sh SEE ALSO
.Xr plakar 1
