.Dd November 3, 2024
.Dt PLAKAR STDIO 1
.Os
.Sh NAME
.Nm plakar stdio
.Nd Start Plakar server in stdio mode
.Sh SYNOPSIS
.Nm
.Op Fl no-delete
.Sh DESCRIPTION
The
.Nm
command starts the Plakar server in standard input/output (stdio) mode, allowing interaction with Plakar over stdio streams. This command can be used for environments where communication is expected to occur over pipes or other stdio-based mechanisms.

.Bl -tag -width Ds
.It Fl no-delete
Disables delete operations. When specified, the server will reject any requests that attempt to delete data.

.El

.Sh ARGUMENTS
None.

.Sh EXAMPLES
To illustrate usage:

.Bl -tag -width Ds
.It Basic example to start the server in stdio mode:
.Bd -literal -offset indent
plakar stdio
.Ed

.It Start stdio mode with delete operations disabled:
.Bd -literal -offset indent
plakar stdio -no-delete
.Ed
.El

.Sh DIAGNOSTICS
.Ex -std
.Bl -tag -width Ds
.It 0
Command completed successfully.
.It >0
An error occurred while starting the stdio server or due to an invalid configuration.
.El

.Sh SEE ALSO
.Xr plakar 1
