.Dd November 3, 2024
.Dt PLAKAR MOUNT 1
.Os
.Sh NAME
.Nm plakar mount
.Nd Mount a Plakar snapshot as a read-only filesystem
.Sh SYNOPSIS
.Nm
.Ar mountpoint
.Sh DESCRIPTION
The
.Nm
command mounts a Plakar repository snapshot as a read-only filesystem at the specified
.Ar mountpoint .
This allows users to access snapshot contents as if they were part of the local file system, providing easy browsing and retrieval of files without needing to explicitly restore them.

This command requires a Linux or Darwin (macOS) environment.

.Bl -tag -width Ds
.It Ar mountpoint
Specifies the directory where the snapshot will be mounted. The directory must exist and be accessible, or an error will occur.

.El

.Sh OPTIONS
No additional options are available for this command.

.Sh ARGUMENTS
.Bl -tag -width Ds
.It Ar mountpoint
A required argument specifying the directory to which the snapshot will be mounted.
.El

.Sh EXAMPLES
To illustrate usage:

.Bl -tag -width Ds
.It Mount a snapshot to the specified directory:
.Bd -literal -offset indent
plakar mount /path/to/mountpoint
.Ed
.El

.Sh DIAGNOSTICS
.Ex -std
.Bl -tag -width Ds
.It 0
Command completed successfully.
.It >0
An error occurred, such as an invalid mountpoint or failure during the mounting process.
.El

.Sh SEE ALSO
.Xr plakar 1
